//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enterprises
    {
        public Enterprises()
        {
            this.Suppliers = new HashSet<Suppliers>();
        }
    
        public int enterpID { get; set; }
        public string nameEnt { get; set; }
    
        public virtual ICollection<Suppliers> Suppliers { get; set; }
    }
}
