//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int ordDetID { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<int> prodID { get; set; }
        public int quantity { get; set; }
        public decimal unitPrice { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
