//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Favorites = new HashSet<Favorites>();
            this.Cart = new HashSet<Cart>();
        }
        public string CurrentPhoto
        {
            get
            {
                if (String.IsNullOrEmpty(imageE) || String.IsNullOrWhiteSpace(imageE))
                    return @"\Images\nofoto.jpg";
                else
                    return @"\Images\" + imageE;
            }
        }
        public int prodID { get; set; }
        public Nullable<int> suppID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string imageE { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual ICollection<Favorites> Favorites { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
    }
}
