//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public Suppliers()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int suppID { get; set; }
        public Nullable<int> enterpID { get; set; }
        public string FIO { get; set; }
        public string phone { get; set; }
        public string emailE { get; set; }
        public string addres { get; set; }
    
        public virtual Enterprises Enterprises { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
