//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Orders = new HashSet<Orders>();
            this.Favorites = new HashSet<Favorites>();
            this.Cart = new HashSet<Cart>();
        }
    
        public int userID { get; set; }
        public Nullable<int> roleID { get; set; }
        public string FIO { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string emailU { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Favorites> Favorites { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
    }
}
